//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveNightsAtFreddy.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CameraScreen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CameraScreen()
        {
            this.Report = new HashSet<Report>();
        }
    
        public int Id { get; set; }
        public int CameraId { get; set; }
        public byte[] Screen { get; set; }
        public Nullable<int> AnimatronicId { get; set; }
    
        public virtual Animatronic Animatronic { get; set; }
        public virtual Camera Camera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Report { get; set; }
    }
}
