//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveNightsAtFreddy.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FiveNightAtFreddyEntities : DbContext
    {
        public FiveNightAtFreddyEntities()
            : base("name=FiveNightAtFreddyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animatronic> Animatronic { get; set; }
        public virtual DbSet<Camera> Camera { get; set; }
        public virtual DbSet<CameraLog> CameraLog { get; set; }
        public virtual DbSet<CameraScreen> CameraScreen { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
